// This file is auto-generated by the AI Schema Architect.
import badge from './objects/badge'
import button from './objects/button'
import companylogo from './documents/companylogo'
import ctasection from './objects/ctasection'
import feature from './documents/feature'
import featuressection from './objects/featuressection'
import footer from './documents/footer'
import footerlink from './objects/footerlink'
import footerlinkcolumn from './objects/footerlinkcolumn'
import header from './documents/header'
import herosection from './objects/herosection'
import metric from './documents/metric'
import metricssection from './objects/metricssection'
import page from './documents/page'
import persondetails from './objects/persondetails'
import quotesection from './objects/quotesection'
import seo from './objects/seo'
import siteSettings from './documents/site-settings'
import socialproofsection from './objects/socialproofsection'

export const schemaTypes = [
  badge,
  button,
  companylogo,
  ctasection,
  feature,
  featuressection,
  footer,
  footerlink,
  footerlinkcolumn,
  header,
  herosection,
  metric,
  metricssection,
  page,
  persondetails,
  quotesection,
  seo,
  siteSettings,
  socialproofsection,
];
