// This file is auto-generated by the AI Schema Architect.
import badge from './objects/badge'
import button from './objects/button'
import companylogo from './documents/companylogo'
import ctasection from './objects/ctasection'
import featureitem from './documents/featureitem'
import featuressection from './objects/featuressection'
import footer from './documents/footer'
import footerlink from './objects/footerlink'
import footerlinkcolumn from './objects/footerlinkcolumn'
import header from './documents/header'
import herosection from './objects/herosection'
import logo from './objects/logo'
import metricitem from './documents/metricitem'
import metricssection from './objects/metricssection'
import navigationlink from './objects/navigationlink'
import page from './documents/page'
import quotesection from './objects/quotesection'
import siteSettings from './documents/site-settings'
import socialproofsection from './objects/socialproofsection'

export const schemaTypes = [
  badge,
  button,
  companylogo,
  ctasection,
  featureitem,
  featuressection,
  footer,
  footerlink,
  footerlinkcolumn,
  header,
  herosection,
  logo,
  metricitem,
  metricssection,
  navigationlink,
  page,
  quotesection,
  siteSettings,
  socialproofsection,
];
