// This file is auto-generated by the AI Schema Architect.
import badge from './objects/badge'
import button from './objects/button'
import companylogo from './documents/companylogo'
import ctasection from './objects/ctasection'
import feature from './documents/feature'
import featuressection from './objects/featuressection'
import footer from './documents/footer'
import footerlink from './objects/footerlink'
import footerlinkscolumn from './documents/footerlinkscolumn'
import header from './documents/header'
import herosection from './objects/herosection'
import imagecomponent from './objects/imagecomponent'
import metric from './documents/metric'
import metricssection from './objects/metricssection'
import navlink from './objects/navlink'
import page from './documents/page'
import quotesection from './objects/quotesection'
import siteSettings from './documents/site-settings'
import socialproofsection from './objects/socialproofsection'
import textblock from './objects/textblock'

export const schemaTypes = [
  badge,
  button,
  companylogo,
  ctasection,
  feature,
  featuressection,
  footer,
  footerlink,
  footerlinkscolumn,
  header,
  herosection,
  imagecomponent,
  metric,
  metricssection,
  navlink,
  page,
  quotesection,
  siteSettings,
  socialproofsection,
  textblock,
];
